
FROM python:3.11

WORKDIR /app

COPY pyproject.toml .
COPY backend/ ./backend/

RUN pip install -U pip
RUN pip install django-tenants psycopg2-binary django djangorestframework pillow python-decouple channels django-cors-headers

EXPOSE 5000

CMD ["python", "backend/main.py", "runserver", "0.0.0.0:5000"]
